spring:
  application:
    name: aeroport

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  profiles:
    active: dev
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: j3+uBG8DHPZrfYViHPHlJ0bWY0Rz9iB6/cymcJBgOs7+vOePp1Lr1YUuUQkrKqnnFqI57q9MnOp1Glz5Mw6yAg==
        # Token is valid 24 hours
        token-validity-in-seconds: 2592000
        token-validity-in-seconds-for-remember-me: 2592000
        refresh-token-validity-in-seconds: 7776000

springdoc:
  packages-to-scan: aeroport.bf.controller
  paths-to-match: ["/api/**"]
  api-docs:
    path: /aeroport-bf-api-docs
  swagger-ui:
    filter: true
    try-it-out-enabled: false
    operations-sorter: method
    tags-sorter: alpha

logging:
  level:
    org.springframework.web: ERROR
    aeroport.bf.config.security.jwt: DEBUG
    aeroport.bf: DEBUG
    org.hibernate: ERROR
    org: INFO
    root: WARN

files:
  upload:
    # baseDir: C:\Users\USER\Documents\identite
    baseDir: C:\Users\dgsi\Documents\identite\identite
    